sudo: required
dist: xenial
language: python
cache: pip

install:
  - python setup.py sdist
  - python setup.py install
  - pip install pytest pytest-cov pytest-xdist requests coveralls codacy-coverage
  - pip install --ignore-installed pytest>=4.4.0
  - pytest --version

script:
  - python setup.py test -a '--cov-config .coveragerc --cov=json_to_models -m "not no_expected" test/'

after_success:
  - coverage xml
  - coveralls
  - python-codacy-coverage -r coverage.xml

matrix:
  include:
    - python: 3.7
    - python: 3.8
    - python: 3.8-dev
    - python: 3.9-dev

deploy:
  - provider: pypi
    user: bogdandm
    password:
      secure: bfIiVsBVMRAjsZYT/UtvNFiY5RU9+2b8QyveKXB3JhZCC/+S8nU/ZJkM9/3Q4V9sUVTVd+NR4Iq1OWkgFwYhJXK+eYlqWJDwfzcxTY5sXAcIxtmXGpNKJaqOF8hyCRdeusGFXR9O1RqzZVQ1ioLCj43eOkjvgFbOw2pIRtmG8Sip6oSJUmY9MSYHFzz4EoY6s+Jv9g30P7bSGY9bekOySFi7LmnX2IM+2T7AMuRvRyd4gHlLVy7pxZxj3S/jz9IiwkVq55HUl5ITWCZVrk6RnYiQhWn5D1AllrOilJGCNQ6HmKQWhDu/fNXEg24BFUTs87OymPKAFNRFniaH9PGu5v2yoN0BWN6+23c2Zc/G9QpQzqm+eVIpW5pkp25EiQw8Cz1pjDmLAVzSZuPXxJnpmkihLUAmSoktI4Zo6+QeLaBoqxds//aLqupMPhO3kzUZe1O5CrogPXTCwpHUGKzMxtjaaXdLo3z7EVT8kRDRtggpdE9KD1shDRUMBrakmuOFA+Tms+iKZSBrW5xhC2g/lFnZluZidj2ir8hyJ9lPMUmGxn/OkIQIBcMkEKCsDFC3wPD39MY/eDbkBvmK++Uhah9T0ljLOR+j1n2ZoJ+N3zD/UpucW5681dGA/sDpgjyDc9ESj14IHjTPLI7sw3IXaial4X2h0ZdfXf6NesLDraI=
    on:
      tags: true
      all_branches: false
    skip_existing: true

  - provider: releases
    api_key:
      secure: AalzD76UPcpYdW0EqIbIi0prnxj1rsyRI6S4EBx91XGFY+BRJV+wJ99MiCE36A4q+cerDCxLmosiAQdzYkJ6/1ageezytJYD0FiC8GxvXtWoutySi0Ka1UTxvIQY22680lh5Xj4vki8tmQAMiLc9gTtwkk+e1J6bPgbQVNQtd5HD3697fdbeBrK70kzHUt93nW1x3N6Ers+WuLtZzV8ft1QzKGQYqgEGigV3rfCM6BThhOXq8B5DnzwwRHg/4TbHvtjyqKchPSzj9+zxGrInJ4dMAut8sGbvFRypDS8Y/I0ODveEBbbmi1SQkoRTH7OuP76T1qAPurmYR2nhq1owxQ4OLjDLgtSiFyzLTEXTjFAOENa8vlZcwC75iCyun/jj2lBVFvW/1rAIiogHxwLsKELbRZQzfY8pTJK5D5KPLNMtNDYecrxI0Bg0z7RPRjk5cpT3gAIyRHuVqCeXZUh+bP87Ev632jtK0thilF67vJNfSamHxLJZH6hEQNKOMjztcOdRDlY+vNbIVwl/RScrhSi+dQCH6FAINXNL9a6TENkwxYjgHYhB9xxNQXq6p+miSID7V9ptBTDVsNIGcv8xLzaChVWExzkFR/BflObjccKmiN9hTlzHSEUaRBpw3EX/L9YNKtPHvPSo/1KxZPt+AB/z0OgvWqSdNaVVtopooQg=
    file_glob: true
    file: dist/*
    skip_cleanup: true
    overwrite: true
    draft: true
    name: ${TRAVIS_TAG} (draft)
    on:
      repo: bogdandm/json2python-models
      tags: true
      all_branches: false
